sudo: required

services:
  - docker

before_install:
  - docker build -t taylorzhangyx/taylorreact -f Dockerfile.dev .

script:
  - docker run -e CI=true taylorzhangyx/taylorreact npm run test

deploy:
  provider: elasticbeantalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-167789202206"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id:
    secure: "$AWS_ACCESS_ID"
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET"